version: "3.9"
services:
  paddle:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/code/
    ports:
      - 888
      - 8080:8080
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "docker"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
